# Generated by Django 3.2.3 on 2021-05-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': 'ToDos'},
        ),
    ]
