# Generated by Django 3.2.3 on 2021-06-01 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_todo_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_date',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='todo',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
